version: "3.1"
services:

  mysql:
    image: mysql:8.0
    command:
      - "--default-authentication-plugin=mysql_native_password"
    container_name: streamstats-mysql
    volumes:
      - ./docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=streamstats
      - MYSQL_USER=streamstats
      - MYSQL_PASSWORD=streamstats
    ports:
      - "8083:3306"

  webserver:
    build: docker/nginx
    container_name: streamstats-webserver
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/data/logs/nginx/:/var/log/nginx/
    ports:
#      - "8080:80"
      - "8443:443"
    depends_on:
      - php-fpm

  php-fpm:
    build: docker/php-fpm
    container_name: streamstats-php-fpm
    working_dir: /application
    volumes:
      - .:/application
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=streamstats
      - DB_USERNAME=streamstats
      - DB_PASSWORD=streamstats
      - PHP_IDE_CONFIG=serverName=streamstats
      - XDEBUG_MODE=debug
      - XDEBUG_CONFIG=client_host=host.docker.internal
